spring.application.name=LogService
server.port=8081

###### MongoDB Configuration #####

#mongodb.base.url=mongodb://dtugpassRa:DtugpassRa%40753@localhost:27193

# mongodb.base.url=mongodb://dtugpassRa:DtugpassRa%40753@164.52.195.217:27193,10.4.72.13:27193
mongodb.base.url=mongodb://dtugpassRa:DtugpassRa%40753@164.52.195.217:27193
mongo.url=mongodb://dtugpassRa:DtugpassRa%40753@164.52.195.217:27193

#spring.data.mongodb.uri=mongodb://trust:trust123@164.52.214.184:27017/admin

spring.data.mongodb.uri=${mongodb.base.url}/admin

replicaSet=rs0&authSource=admin&readPreference=primaryPreferred


# MongoDB URI for admin-log database #
spring.data.mongodb.admin-log.uri=${mongodb.base.url}/admin-log?authSource=admin

# MongoDB URI for enterprise-log database #
spring.data.mongodb.enterprise-log.uri=${mongodb.base.url}/enterprise-logs?authSource=admin

# MongoDB URI for kyc-log database #
spring.data.mongodb.kyc-log.uri=${mongodb.base.url}/kyc-log?authSource=admin

# MongoDB URI for central-log database #
spring.data.mongodb.central-log.uri=${mongodb.base.url}/central-log?authSource=admin

# MongoDB URI for signing-portal-log database #
spring.data.mongodb.signing-portal-log.uri=${mongodb.base.url}/signing-portal-log?authSource=admin

# MongoDB URI for signing-log database #
spring.data.mongodb.signing-log.uri=${mongodb.base.url}/signing-log?authSource=admin

# MongoDB URI for ra-log database #
spring.data.mongodb.ra-log.uri=${mongodb.base.url}/ra-log?authSource=admin

# MongoDB URI for payments-log database #

spring.data.mongodb.payments-log.uri=${mongodb.base.url}/payments-log?authSource=admin

# MongoDB URI for ob-log database #
spring.data.mongodb.ob-log.uri=${mongodb.base.url}/ob-log?authSource=admin

# MongoDB URI for authn-log database #
spring.data.mongodb.authn-log.uri=${mongodb.base.url}/authn-log?authSource=admin

###### RabbitMQ Server Connection properties ########################


# Queue configuration for admin-log #
admin-log.queue=admin-log

enterprise-log.queue = enterprise-logs

kyc-log.queue = kyc-log

# Central log queue configuration #
central-log.exchange=/
central-log.queue=central-log
central-log.routingkey=central-log

# Signing Portal log queue configuration #
service-log.queue=signing-portal
service-log.exchange=/

# Signing Portal log queue configuration #
signing-log.queue=signing-log
signing-log.exchange=/

# Ra log queue configuration #
ra-log.queue=ra-log
ra-log.exchange=/

# Payments log queue configuration #
payments-log.queue=payments-log
payments-log.exchange=/

# Ob log queue configuration #
ob-log.queue=ob-log
ob-log.exchange=/

# Authn log queue configuration #
authn-log.queue=authn-log
authn-log.exchange=/

# Additional settings #
spring.main.allow-bean-definition-overriding=true
spring.jackson.serialization.write-dates-as-timestamps=false
spring.data.mongodb.auto-index-creation=true

central.signing-failed.url=http://localhost:8088/log-service/central-log/api/audit-logs/signing-failed
spring.banner.location=classpath:/banner.txt



#Kafka config::
# Kafka bootstrap server
kyc.log.topic=kyc-log-topic
admin.log.topic=admin-logs-topic
auth.log.topic=auth-logs-topic
enterprise.log.topic=enterprise-logs-topic
ob.log.topic=ob-logs-topic
payments.log.topic=payments-logs-topic
ra.log.topic=ra-logs-topic
signing.log.topic=signing-logs-topic
service.log.topic=signing-portal-topic
central.log.topic=central-log-topic
#spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.bootstrap-servers=164.52.195.217:9096,164.52.195.217:9097,164.52.195.217:9098



# Kafka consumer group id
spring.kafka.consumer.group-id=kyc-logs

#logging.level.org.springframework.kafka=DEBUG
#logging.level.org.apache.kafka=DEBUG
# This logs the actual BSON commands sent to the server
#logging.level.org.mongodb.driver.protocol.command=DEBUG

spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.dtt.logs.dto.service.AuditDTO

logging.level.org.apache.kafka=OFF
logging.level.org.springframework.kafka=OFF
logging.level.kafka=OFF

# Force Jackson to serialize all dates using UTC
spring.jackson.time-zone=UTC
# Ensure dates are strings (ISO-8601) and not numbers

